version: '3.7'
services:
  db:
    image: mysql:5.7.25
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
    ports:
      - "13306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
